[versions]
agp = "8.11.1"
coilCompose = "2.7.0"
converterGson = "2.9.0"
koinAndroid = "3.5.3"
koinAndroidVersion = "3.5.0"
koinAndroidxCompose = "3.5.3"
koinAndroidxComposeVersion = "3.5.0"
kotlin = "2.0.21"
kotlinCompose = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
appcompat = "1.7.1"
material = "1.12.0"
retrofit = "2.9.0"
uiGraphicsAndroid = "1.8.3"
uiTextAndroid = "1.8.3"
material3Android = "1.3.2"
uiToolingPreviewAndroid = "1.8.3"
navigationRuntimeAndroid = "2.9.3"
runtimeAndroid = "1.8.3"
navigationComposeJvmstubs = "2.9.3"
navigationComposeAndroid = "2.9.3"
roomCommonJvm = "2.7.2"
roomVersion = "2.7.2"
roomRuntimeAndroid = "2.7.2"
androidxRoomRuntime = "androidx.room:room-runtime:2.6.1"
androidxRoomCompiler = "androidx.room:room-compiler:2.6.1"
androidxRoomKtx = "androidx.room:room-ktx:2.6.1"
navigationRuntimeKtx = "2.9.3"
koinBom = "3.5.3"
mockk = "1.13.10"
coroutinesTest = "1.8.0"
turbine = "0.12.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
insert-koin-koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroidVersion" }
io-insert-koin-koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroidxComposeVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
koin-android = { module = "org.koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "org.koin:koin-androidx-compose", version.ref = "koinAndroidxCompose" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
androidx-ui-text-android = { group = "androidx.compose.ui", name = "ui-text-android", version.ref = "uiTextAndroid" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
androidx-ui-tooling-preview-android = { group = "androidx.compose.ui", name = "ui-tooling-preview-android", version.ref = "uiToolingPreviewAndroid" }
androidx-navigation-runtime-android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }
androidx-runtime-android = { group = "androidx.compose.runtime", name = "runtime-android", version.ref = "runtimeAndroid" }
androidx-navigation-compose-android = { group = "androidx.navigation", name = "navigation-compose-android", version.ref = "navigationComposeAndroid" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
androidx-room-common-jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
retrofit2 = { module = "com.squareup.retrofit2:retrofit", version = "2.9.0" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version = "2.9.0" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinCompose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose.compiler", version = "1.5.15" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.5" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.1" }
jacoco = { id = "jacoco" }
android-library = { id = "com.android.library", version.ref = "agp" }
